18F/identity-terraform

vpc_flow_cloudwatch_filters/main.tf
... which is timed out connections from other servers to the outbound proxy.
=> Also ignore source port 3128... 

kms_log/main.tf, kms_log/output.tf, kms_log/variables.tf
https://github.com/18F/identity-devops/issues/1236
=> Terraform module for KMS decryption event processing

kms_log/main.tf
Prior conditional fix didn't work entirely.  Build the arn so it isn't dependent on the resource being created.
=> Updates to fix conditional failure

kms_log/main.tf, squid_cloudwatch_filters/main.tf
Add dependencies for 2 log groups.  env_/var/log/squid/access.log and env_/srv/idp/shared/log/kms.log
https://github.com/18F/identity-devops/issues/1510
https://github.com/18F/identity-devops/issues/1509
=> Add dependencies for log groups

kms_log/main.tf
Add useful backlog metrics to dashboard.
Alert on excessive backlog.
=> Add more monitoring and alerting to KMS logging

kms_log/main.tf
... relatively large batches to process.
https://github.com/18F/identity-devops/issues/1658
=> Allow 120 seconds in case there's a backlog. In that case we get

cloudwatch_dashboard_rds/main.tf, iam_assumerole/main.tf, kms_log/main.tf
These changes should only be whitespace, the plan should not change. You can use the code review function to toggle between ignore whitespace to check.  Related to https://github.com/18F/identity-devops/issues/2111
=> Run terraform fmt, whitespace changes

ssm/README.md, ssm/main.tf
This is a module which could enable further SSM features as needed.  Required for https://github.com/18F/identity-devops/issues/2109
=> Add SSM Sessions Support

lambda_pipeline/README.md, lambda_pipeline/codebuild.tf, lambda_pipeline/codepipeline.tf, lambda_pipeline/main.tf, lambda_pipeline/variables.tf
Created for identity-devops issue https://github.com/18F/identity-devops/issues/2855
=> Pipeline for Lambda functions built with CircleCi

slack_lambda/main.tf
Permits deployment to multiple regions
Supports Issue https://github.com/18F/identity-security-private/issues/1809
=> Change Role name to name_prefix in SNS topics

config_fedramp_conformance/main.tf
Update 3 Fedramp config rules to correct rule source
Issue https://github.com/18F/identity-devops/issues/2900
=> Fix Config rules for Fedramp

lambda_pipeline/codebuild.tf, lambda_pipeline/codepipeline.tf, lambda_pipeline/variables.tf
Update lambda-pipeline to allow template and code artifacts to be stored in different buckets. 
Issue https://github.com/18F/identity-devops/issues/2973
=> Update lambda-pipeline module

squid_cloudwatch_filters/main.tf
Issue https://github.com/18F/identity-devops/issues/3143
=> Add proxy alarm for total requests

slack_lambda/lambda.py, slack_lambda/main.tf
add formatting rule so that slack messages from codepipeline are actually readable
=> slack message formatting

launch_template/main.tf
Issue https://github.com/18F/identity-devops/issues/2948
=> Require imdsv2 in launch templates

launch_template/main.tf, launch_template/output.tf, launch_template/variables.tf
-change static name to  name_prefix which will append a random string to the end of the template name
Calling modules will not be able to guess the name, and must use of the the available output variable
=> change launch_template to use name_prefix

slo_lambda/main.tf, slo_lambda/variables.tf
Two unrelated changes that both involve the word "prefix"
=> Tweak the default value and description of sli_prefix

elb_access_logs_bucket/main.tf
Apparently, you need these services for an NLB to log.  I don't quite understand this, because it's not in the docs, but I found variations on this policy in several places on the internets.
=> add some perms so that nlb can log

ssm/main.tf, ssm/variables.tf
This PR adds parameter support to our SSM Command Documents.
Addresses [identity-devops#5017](https://github.com/18F/identity-devops/issues/5017)
=> Adding Parameter Support to SSM

ssm/main.tf, ssm/variables.tf
Modifications necessary for ssm command documents to work properly.
=> Pb ssm command

elb_access_logs_bucket/main.tf
https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-access-logs.html?icmpid=docs_elbv2_console
=> Change ELB S3 Bucket Encryption To Support NLBs

launch_template/output.tf
- adds latest_version to terraform outputs to allow ASG auto refresh downstream
=> Launch Template Output Fixups

iam_assumerole/README.md, iam_assumerole/data.tf, iam_assumerole/main.tf
This adds permissions boundary to the admin, analytics, billing, escrow read, fraudops, kms, power, readonly, reports, soc, supporteng, terraform roles. This is just updating the module.
=> Initial Commit - Adding permission boundary

kms_keymaker_multiregion_primary/cloudwatch.tf, kms_keymaker_multiregion_primary/sns.tf, kms_keymaker_multiregion_replica/cloudwatch.tf, kms_keymaker_multiregion_replica/sns.tf
- updates kms mr modules to not overlap resource names with existing kms module
=> KMS Fix Overlapping Resources

kms_log/main.tf, kms_log/variables.tf
This PR migrates the KMS Lambda Source code from an S3 storage to directly upload zip files.
Addresses #https://github.com/18F/identity-devops/issues/5412
=> KMS Lambda MonoRepo Migrations

kms_log/aggerate_notify.tf, kms_log/main.tf, kms_log/variables.tf
This PR creates the necessary infrastructure to queue notifications for batching. 
Addresses #https://github.com/18F/identity-devops/issues/5974
=> KMS Notification Aggregation

kms_keymaker_multiregion_primary/kms.tf, kms_keymaker_multiregion_primary/main.tf, kms_keymaker_multiregion_replica/kms.tf, kms_keymaker_multiregion_replica/main.tf
- limit use of KMS keys within account boundaries and within region boundaries
=> Update KMS Key Policy

kms_keymaker/versions.tf, kms_keymaker_multiregion_primary/versions.tf, kms_keymaker_multiregion_replica/versions.tf
Remove versions.tf from KMS modules to prevent orphaning resources and issues later
=> Remove Versions.tf From KMS Modules

kms_log/main.tf, kms_log/variables.tf
This PR adds configuration variables to the KMS Log module Cloudwatch Processor.
=> KMS Log Cloudwatch Processor Memory Configuration Variables

kms_log/main.tf, kms_log/variables.tf
This PR redefines existing lambda environment variables and adds new ones to support the new debug mode defined in:
https://github.com/18F/identity-devops/pull/6567
Partially Addresses #https://github.com/18F/identity-devops/issues/5916
=> KMS Log Cloudtrail Lambda Debug Support

lambda_alerts/main.tf
This PR switches from attempting to detect if the lambda insights layer is available to a variable control.
=> Lambda Alerts : Insights Enabled Variable

kms_log/main.tf, lambda_alerts/main.tf
This PR updates the lambda_alerts submodule inside kms_log to incorporate new the variable insights_enabled.
=> KMS Log: Update Lambda Alert Submodule.
