acm_certificate/README.md
acm_certificate/main.tf

This is useful because Terraform has some rather arcane syntax for
referring to lists and arbitrary numbers of SubjectAltNames, so the
module is very helpful to tie it all together including DNS validation
in a convenient way.

Add a module for creating ACM certificates.

---

launch_template/README.md
launch_template/main.tf

Launch templates are much like the older ASG Launch Configurations, but they are versioned so that changes don't have to create an entirely new resource, and they can be used to create instances outside an ASG as well as within an ASG.

Add a module for creating launch templates.

---

kms_log/main.tf

On first deployment when logging isn't enabled, terraform cannot create queue policy due to reference that doesn't exist.  
Error text
* module.kms_logging.data.aws_iam_policy_document.sqs_kms_ct_events_policy: Resource 'aws_cloudwatch_event_rule.decrypt' not found for variable 'aws_cloudwatch_event_rule.decrypt.arn'
Add conditional expression to queue policy creation.

Don't create queue policy if kms logging is not enabled

---

kms_log/main.tf
kms_log/variables.tf

Add CloudWatch dashboard.  Add alarm for messages on dead letter queue.
https://github.com/18F/identity-devops/issues/1236

Add dashboard and alarm for kms logging

---

kms_log/main.tf

1. Rename Lambdas to match what's in https://github.com/18F/identity-cloudlib-lambdas/blob/master/cloudlib.identity-lambda-functions.yaml
2. Cloudtrail events come from the decryption_event_rule, not from kmslog_event_rule.
3. event pattern source must be an array
4. Give each aws_iam_role_policy a unique name and SID. I am not sure but I think these were stepping on each other.
5. Fix all Lambda environment variables to match what's in the Lambda code.
6. Correct the class name for the event generator Lambda.

Minor fixes

---

kms_log/main.tf

This appears to be necessary according to https://stackoverflow.com/questions/5926774/sns-topic-not-publishing-to-sqs
AWS documentation wants us to use * as the principal: https://docs.aws.amazon.com/sns/latest/dg/sns-sqs-as-subscriber.html#SendMessageToSQS.sqs.permissions
But I like this way better.

Use the service principal instead of the account principal

---

kms_log/main.tf

Add the environment to the event rule.  Currently all of the event rules are matching on the same criteria causing multiple deliveries to the SNS topic.

Fix event rule firing for every environment

---

kms_log/variables.tf

Update CloudWatch filter to include only decryption events.
Tested by adding new account or attempting to logon as a user that doesn't exist.
https://github.com/18F/identity-devops/issues/1460

Update filter to exclude encrypt events

---

acm_certificate/main.tf

Terraform is perpetually recreating certain AWS ACM certificates because
the AWS API has started returning the list of subjectAltNames in a
nondeterministic order.
Work around this for the time being by ignoring changes to the
subjectAltNames. We will need to delete this line if we want to make
changes to the subjectAltNames in the future.
https://github.com/18F/identity-devops/issues/1469

Workaround for TF/AWS bug: Ignore changes in sANs.

---

cloudwatch_dashboard_alb/main.tf

Refactor the ALB dashboard to provide significantly more useful
information, especially for CPU-based autoscaling.
- Factor out the region to a variable so this module is region-independent.
- Tweak labels to emphasize which metrics are frontend ELB vs backend
target group metrics.
- On frontend ELB errors graph, show 3xx and 4xx errors in addition to
5xx. This will allow us to better notice things like the WAF blocking
requests and returning 4xx errors.
- On response time graph, remove the mean graph line and replace it with
p50, p90, and p99 lines. Percentiles are much more representative of
the underlying data, especially for our use case. Our response time
histogram is bimodal: most requests are for static assets served by
nginx, and response time is extremely fast. But a significant …

Add major new info to cloudwatch ALB dashboard.

---

acm_certificate/main.tf
acm_certificate/versions.tf
asg_lifecycle_notifications/main.tf
asg_recycle/main.tf
cloudwatch_dashboard_alb/main.tf
cloudwatch_dashboard_rds/main.tf
elb_access_logs_bucket/main.tf
elb_access_logs_bucket/outputs.tf
elb_access_logs_bucket/variables.tf
elb_http_alerts/main.tf
kms_log/main.tf
kms_log/output.tf
kms_log/variables.tf
lambda_alerts/main.tf
launch_template/main.tf
squid_cloudwatch_filters/main.tf
state_bucket/main.tf
vpc_flow_cloudwatch_filters/main.tf

This is an omnibus PR covering all of the style/syntax changes to the `terraform-common` templates that were necessary in order to upgrade our infrastructure to Terraform 0.12.
Due to the structure of our infrastructure, and the way that `tf-deploy` resolves all of the necessary dependencies when it calls `terraform apply`, the `terraform 0.12upgrade` tool couldn't be used within this repo. Therefore, I've manually edited files within this repo whenever issues were encountered while running `terraform` commands.

Terraform v0.12 upgrade

---

iam_assumerole/README.md
iam_assumerole/main.tf

This Terraform module is designed to create all of the IAM resources necessary for cross-account AssumeRole access, via:
- a role that can be assumed by any IAM user in a 'master' account with access to assume that role (via user/group privileges)
- one or more policy documents dictating access via `statement{}` blocks
- one or more policies created from the policy document(s)
- one or more attachments of the role to the policy(ies)
- (optionally) additional attachment(s) if there are other IAM policies that should be attached to the assumable role
Full information, including variable names and a working example, can be found within `iam_assumerole/README.md`. Please note that this module requires Terraform ~> 0.12 in order to work properly.

iam_assumerole: module for creating cross-account AssumeRole access via IAM

---

lambda_alerts/main.tf

The `aws_cloudwatch_metric_alarm` for Lambda error rates depends on the existence of a Lambda function; if this function does not already exist, Terraform will complain for both the CloudWatch resource and the Lambda `function_name` data source.
This PR integrates the following changes:
1. The variable `enabled` is used as a `count` conditional to determine whether or not to create the CloudWatch alarm. Defaults to 1; if set to 0, the alarm will not be created.
2. The `aws_lambda_function` data source has been removed, as it would error out if it could not get a `function_name` and does not depend on `enabled`. This data source was originally used as the conditional; it is likely that this behavior has changed in Terraform 0.12, hence why it no longer works.

use 'enabled' flag to determine whether or not to create lambda alerts

---

kms_log/main.tf
kms_log/variables.tf

In Terraform 0.11, `null_resource` blocks were used to force `data` sources to depend upon resources created by other Terraform modules. As a result of this, however, the data sources were read upon EVERY Terraform run, meaning that `terraform plan` ***always*** contained "changes" in its output (though nothing actually NEEDED to be changed).
This PR moves the resource dependencies to the `kms_log` module in this repo. After moving the state addresses and running one more `apply`, the `plan` output is now clear!

moving keymaker + KMS policy doc here to eliminate terraform-plan noise

---

ses_dkim_r53/README.md
ses_dkim_r53/main.tf

Given a domain name and a Route53 zone ID, this Terraform module will create:
- an SES identity resource for the provided domain + corresponding Route53 TXT verification record
- three (3) SES domain DKIM generation resources for the provided domain + corresponding Route53 CNAME records
Additional information provided in the associated `README.md` file.

module "ses_dkim_r53" : SES domain identity management

---

iam_assumegroup/README.md
iam_assumegroup/main.tf
iam_masterassume/README.md
iam_masterassume/main.tf
iam_masterusers/README.md
iam_masterusers/main.tf

This PR creates two new Terraform modules, `iam_assumegroup` and `iam_masterassume modules`, which can be respectively used to:
1. Create an AWS IAM Group, with a specified list of users and generated ARNs for per-account-type Assume-Role-access IAM policies
2. Create an IAM policy(ies) for assuming access to specific roles within a category of AWS accounts
The "account type" concept allows for more granular control of permissions for IAM groups across multiple categories -- or "types" -- of AWS accounts. As an example:
An organization has the following accounts:
1. Dev / Infrastructure
2. Dev / S3 Buckets
3. Prod / Infrastructure
4. Prod / S3 Buckets
5. Master
Each account has the same list of roles, e.g.: FullAdmin, PowerUser, ReadOnly, SOCAdmin.
1. 3 AWS accounts for development
2. 2 …

iam_assumegroup + iam_masterassume modules

---

iam_assumegroup/README.md
iam_assumegroup/main.tf
iam_masterassume/README.md
iam_masterassume/main.tf

The `policy_depends_on` variable in `iam_assumegroup` can be used in conjunction with another value, i.e. the output `policy_arns` in the `iam_masterassume` module, to make `iam_assumegroup` wait for specific IAM policies to exist before attempting to create their respective group attachments.
The `iam_assumegroup` module is used to attach IAM policies to groups, and the policies themselves are generated OUTSIDE of this module (and done instead within `iam_masterassume`). Terraform is unable to calculate the proper policy ARNs itself due to this circular dependency, so the `role_group_map` is used with the `master_account_id` to generate the ARN values in the same module.
HOWEVER: If the policies do not already exist before Terraform attempts to create these attachments, the `apply` …

adding depends_on functionality between iam_assumegroup and iam_masterassume

---

iam_assumegroup/README.md
iam_assumegroup/main.tf
iam_masterusers/README.md
iam_masterusers/main.tf

With the previous code, creating new users AND groups simultaneously caused Terraform to fail, as it could not create the `aws_iam_group_membership` resources until both the users AND the groups existed. This adds a "fake" `depends_on` variable to accommodate that scenario.
Also: Adds the `iam:ListAttachedGroupPolicies` permission so that a user can see which policies they can access, based on the group(s) they are in.

fixing dependencies between modules + adding ListAttachedGroupPolicies permission

---

iam_masterusers/README.md
iam_masterusers/main.tf

If using an `aws_iam_policy_attachment` resource to attach the `manage_your_account` policy to a user, Terraform does not understand the relationship between the resources. This means that Terraform will fail when it:
1. attempts to create the policy attachment before the user exists (i.e. creating resources simultaneously)
2. delete the user before the policy attachment is removed (if the attachment's creation is dependent upon the user resource)
This changes the resource to use an `aws_iam_user_policy_attachment` resource instead, allowing it to properly manage both resources in whichever order they are altered.

using aws_iam_user_policy_attachment for manage_your_account resource

---

iam_masterusers/main.tf

Ignore what I said in the last PR because that clearly was false ಠ_ಠ
Makes the `aws_iam_user_policy_attachment` resource utilize the ACTUAL `aws_iam_user.master_user` resource set. Eliminates need for `depends_on` and/or creation/deletion dependencies.

use actual aws_iam_user.master_user resource instead of var.user_map to create aws_iam_user_policy_attachment

---

ses_dkim_r53/README.md
ses_dkim_r53/main.tf

As per my addition to the README:
> To allow for multi-region support, a `aws_route53_record.primary_verification_record` resource must be created separately (i.e. in the parent module), which uses the output value `ses_token` from each instance of `aws_ses_domain_identity.primary`.

moving primary_verification_record out of module for multi-region support

---

kms_log/main.tf
s3_bucket_block/README.md
s3_bucket_block/main.tf

As per the README.md:
This Terraform module is designed to create an S3 bucket, or a set of buckets, from a map variable containing various bucket configurations. It provides consistency for the following, in all buckets provided:
- Bucket naming scheme
- Versioning enabled
- Logging enabled (an S3 'log' bucket is also created)
- KMS SSE
By default, only the bucket's name is needed within the provided `bucket_data` map variable. This is built from:
- `var.bucket_prefix`
- `each.key` (in the `bucket_data` map variable)
- `data.aws_caller_identity.current.account_id`
- `var.region`
The following additional settings can be configured via key-value pairs in the map:
- `acl` (defaults to `private`)
- `policy` (defaults to `""`)
- `force_destroy` (defaults to `true`)
- `lifecycle_rules` (list, …

s3_bucket_block: iterative S3 bucket + block generation

---

s3_bucket_block/main.tf

Since the `s3_bucket_block` module builds its resources from `for_each` loops, it attempts to create the `aws_s3_bucket_public_access_block` resources at the same time that it's creating their respective buckets. This adds a `depends_on` argument, making the module wait until the buckets exist before attempting to create their access blocks.

make aws_s3_bucket_public_access_block wait for bucket to exist

---

kms_keymaker/README.md
kms_keymaker/main.tf
kms_log/main.tf
kms_log/variables.tf

To allow for multi-region support + creation of KMS keys, this PR splits out the necessary resources for the `login-dot-gov-keymaker` KMS key + monitoring into a new module, `kms_keymaker`. This includes:
- KMS key + alias
- CloudWatch event rule on `Decrypt` events with `password-digest` / `pii-encryption` context
- SNS topic + subscription which sends to an SQS queue (created in `kms_log`)
- In-between resources (SNS topic policy, CloudWatch event target, etc.)
`kms_log` has also been updated, primarily to allow the above resources to be abstracted out, and also to grant permissions for SNS (instead of CloudWatch) to send messages to the SQS queue. The new design allows for multi-region message delivery, since a single SQS queue can receive subscription notifications across regions.

splitting out kms_log + kms_keymaker

---

kms_keymaker/README.md
kms_keymaker/main.tf
kms_log/main.tf
kms_log/variables.tf

Removes kmslogging_service_enabled from `kms_log` and `kms_keymaker` modules.
The following state moves are required after which a `plan` should be empty:
~~~
aws-vault exec ACCOUNT -- zsh
export ENVIR=<ENVIRONMENT_NAME>
tf-deploy $ENVIR app state mv \
'module.kms_logging.aws_cloudwatch_event_rule.unmatched[0]' \
'module.kms_logging.aws_cloudwatch_event_rule.unmatched'
tf-deploy $ENVIR app state mv \
'module.kms_logging.aws_cloudwatch_event_target.unmatched[0]' \
'module.kms_logging.aws_cloudwatch_event_target.unmatched'
tf-deploy $ENVIR app state mv \
'module.kms_logging.aws_lambda_function.cloudtrail_processor[0]' \
'module.kms_logging.aws_lambda_function.cloudtrail_processor'
tf-deploy $ENVIR app state mv \
'module.kms_logging.aws_lambda_event_source_mapping.cloudtrail_processor[0]' \ …

Remove kmslogging_service_enabled flag

---

launch_template/main.tf

Adds `use_spot_instances` variable to `launch_template`.  Set to 0 (off) by default.  If set to 1 the launch template will look like:
~~~
~ resource "aws_launch_template" "template" {
~ image_id                             = "ami-074db07a0fa18f24a" -> "ami-00ca1bcc5c98da1af"
~ latest_version                       = 10 -> (known after apply)
~ user_data                            = "*"
+ instance_market_options {
+ market_type = "spot"
+ spot_options {
+ spot_instance_type = "one-time"
~~~

Add use_spot_instances option to launch_template

---

s3_bucket_block/README.md
s3_bucket_block/main.tf

Since the `state_bucket` module already creates an S3 log bucket, it's not necessary to create it here.

removing log bucket creation from s3_bucket_block module

---

s3_batch_inventory/README.md
s3_batch_inventory/main.tf

This Terraform module is designed to add S3 Inventory configurations to all S3 buckets in a given list, as well as an S3 bucket to store the Inventory CSV files. Optionally, it can also create an S3 access log bucket, if one does not already exist, for the Inventory bucket.
Full information available in the `README.md` file.

s3_batch_inventory: add S3 Inventory configs to all buckets in a list

---

s3_batch_inventory/main.tf

Does what it says on the tin. Default sets to `AES256` instead, so that objects can be added without the need for a KMS CMK.

use variable to control SSE algorithm instead of hard-coding

---

asg_recycle/main.tf

Adds `override_spindown_capacity` to force a specific spindown size.
Shrinks normal auto-recycle window to 30 minutes instead of 60.
Related to https://github.com/18F/identity-devops/issues/2846

Add hard scale in option for recycle schedule

---

s3_config/README.md
s3_config/main.tf

Does what it says on the tin. Will simply set the values of all public access block configs to `false` on the bucket the module is directed at.

adding block_public_access variable to disable block if desired

---

slack_lambda/main.tf

Fix permissions issue that is preventing Lambda function from creating CW log group.  This is not directly related to message delivery failure.  Just makes troubleshooting a little more difficult.

Update lambda role to fix cloudwatch logging issue

---

acm_certificate/main.tf
elb_access_logs_bucket/main.tf
s3_bucket_block/main.tf
state_bucket/main.tf

Does what it says on the tin!
This addresses numerous changes, most of which are explained in the [Terraform AWS Provider Version 3 Upgrade Guide](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade). In particular, this also acknowledges [the fix for `domain_validation_options` in the `aws_acm_certificate` resource](https://github.com/terraform-providers/terraform-provider-aws/issues/8531#issuecomment-663562156), which is now read as an unordered set rather than an ordered list (negating the need for our hacky `ignore_changes` workaround!).

updating all modules to work with version 3 of hashicorp/aws Terraform provider

---

elb_access_logs_bucket/main.tf
s3_bucket_block/main.tf

The `s3_bucket_block` and `elb_access_logs_bucket` each utilize the `s3_config` module; the currently-listed commit SHA was squashed and no longer exists. This fixes that.

fixing circular SHA reference

---

kms_log/main.tf
kms_log/variables.tf

Update default Lambda version for new deployments.
Set alarm sns topic to a valid topic.
Add alarms for Lambda failures
Issues https://github.com/18F/identity-devops/issues/3008

Resolve issue with KMS logging alarms

---

kms_log/main.tf

Deployment of new alarms failed.  Needed to add another variable to config.
Deployed to crissupb environment.
Related to issue https://github.com/18F/identity-devops/issues/3008

Deploy of new alarms failed update config

---

slack_lambda/main.tf

Use environment variables instead of inline values in order to update Lambda functions if values change.
Related to issue https://github.com/18F/identity-security-private/issues/1809

Update slack lambda to use environment variables

---

slack_lambda/main.tf

Pull slack webhook url from SSM parameter
Update CloudWatch log configuration
Update Lambda permissions
Related to issue https://github.com/18F/identity-security-private/issues/1809
Will need to update parameter /account/slack/webhook/url with Slack webhook url after deployment.

Fix issues with Slack notifications

---

elb_access_logs_bucket/main.tf
s3_bucket_block/main.tf
s3_config/main.tf
state_bucket/main.tf

Terraform doesn't understand that S3 operations can't be executed simultaneously on the same bucket -- in this case, the public access block and the S3 inventory config. This adds a few `depends_on` lines to make everything wait its turn.

fixing dependencies for public access block/inventory on buckets

---

lambda_pipeline/codebuild.tf

Codebuild cannot read the /account SSM parameters that are used to create Lambda functions.
Issue https://github.com/18F/identity-devops/issues/2989

Add permissions to Codebuild role

---

lambda_pipeline/codepipeline.tf
lambda_pipeline/variables.tf

CloudWatch event and notification on Codepipeline stage failure.
Issue https://github.com/18F/identity-devops/issues/3045

Add alarm for pipeline stage failure

---

lambda_pipeline/codebuild.tf

Add permissions to allow Codebuild to create CloudWatch metrics.
Issue https://github.com/18F/identity-devops/issues/2989

Update Codebuild permissions

---

lambda_pipeline/codepipeline.tf

The name for the CloudWatch event rule `lambda_pipeline_failed` is currently generated using `name_prefix`; however, if the environment name + project name + 'pipeline-failed' + <generated CloudFormation numerical string> is greater than 64 characters, the rule cannot be created.
This changes the resource to name itself using `name`, instead of `name_prefix`.

changing name_prefix to name to avoid name constraints

---

squid_cloudwatch_filters/main.tf

Because Terraform modules can now be created with the `depends_on` conditional, the `log_group_found` null resource is no longer necessary. Additionally, said null resource has, traditionally, operated inconsistently with environment builds/teardowns; using `depends_on` directly with the module declaration has instead provided accurate consistency in deployments.

removing null_resource dependency from squid_cloudwatch_filters

---

slack_lambda/main.tf

No need for versions. Notifications are using $Latest.

Don't publish new version of Slack lambda

---

iam_masterassume/main.tf

Issue https://github.com/18F/identity-devops/issues/3218
Require role session name to match user name

Require role session name and mfa

---

launch_template/main.tf

Require use of instance metadata service v2.
Issue https://github.com/18F/identity-devops/issues/2948

Require imdsv2

---

s3_batch_inventory/README.md
s3_bucket_block/README.md
s3_bucket_block/main.tf
state_bucket/main.tf

Related to issue https://github.com/18F/identity-devops/issues/3466
Create new s3 access logs bucket.  This bucket will replace existing bucket.  Configure lifecycle policy to clear out existing bucket to facilitate deletion in the following release.  Not feasible to write a policy clears out the existing data while writing new data to the bucket.

Create new s3 access logs bucket

---

git2s3_artifacts/README.md
git2s3_artifacts/git2s3.template
git2s3_artifacts/main.tf

New Terraform module that adds the creation of a public-artifacts S3 bucket (with, if desired, multi/cross-account access), with a key pointing to the `OutputBucket` from the Git2S3 CloudFormation Stack. Full details in the README.md
Addresses https://github.com/18F/identity-devops/issues/3129

git2s3_artifacts: cross-account availability for third-party code repo importing

---

iam_assumegroup/main.tf
iam_masterassume/main.tf

If an IAM group doesn't exist at the time Terraform tries to create its `aws_iam_policy_attachment.group_policy` resource(s), the deploy will fail:
```
Error: [WARN] Error updating user, role, or group list from IAM Policy Attachment SandboxAssumeTerraform:
– NoSuchEntity: The group with name socreadonly cannot be found.
```
This adds `aws_iam_group.iam_group` as a dependency for each `aws_iam_policy_attachment.group_policy` for that group -- i.e. all groups must exist first -- thus ensuring that the resources are created and in the right order.
(Also -- a minor syntax fix in `iam_masterassume`, where interpolation of `arn` does not require explicit declaration.)

make IAM policy attachments depend on the group(s) existing first

---

kms_log/main.tf

This got trampled in the Terraform 1.0 upgrade.
Our KMS matchers all have entrypoints of main.MODULE and not
main.Function::MODULE.

Use correct entrypoints for KMS matching Lambdas

---

elb_access_logs_bucket/main.tf
git2s3_artifacts/main.tf
kms_log/main.tf
s3_bucket_block/main.tf
state_bucket/main.tf
versions.tf

Now that Terraform 1.0.2 is the standard everywhere, this removes support for 0.13.7 and other previous versions in the `login.gov` infrastructure. Second commit also updates the self-referencing SHAs (i.e. those using `s3_config`) within this repo.
Addresses https://github.com/18F/identity-devops/issues/3111

removing Terraform 0.13.7 references everywhere

---

dnssec/README.md
dnssec/main.tf
dnssec/outputs.tf
dnssec/variables.tf
dnssec/versions.tf
iam_masterusers/main.tf
versions.tf

This module has been moved into this repo as part of Login.gov's continuing effort to provide Terraform modules that we use to the open-source community.
Detailed information, including available variables, implementation examples, and recommended steps for effective key-signing key (KSK) rotation, is available in the `README` file within the module directory.

creation of 'dnssec' module for configuring/enabling DNSSEC signing for a domain/hosted zone

---

launch_template/main.tf

This is a no-op (though terraform reports a change due to the variable being previously uninitialized) per https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#http_put_response_hop_limit 
Sample plan:
```
~ metadata_options {
~ http_put_response_hop_limit = 0 -> 1
}
}
```

Add variable for response hop limit

---

launch_template/main.tf
versions.tf

Fixes this error, which (surprisingly) was *not* coming up in earlier 1.x.x versions of Terraform (likely because of an older AWS provider version, as well):
```
│ Call to function "list" failed: the "list" function was deprecated in Terraform v0.12 and is no longer available; use tolist([ ... ])
│ syntax to write a literal list.
```

use Terraform 1.1.3 + remove deprecated list() function from launch_template module

---

cloudwatch_dashboard_rds/main.tf

`dev app plan`
~~~
~ resource "aws_cloudwatch_dashboard" "main" {
~ dashboard_body = jsonencode(
~ {
~ widgets = [
~ {
~ properties = {
~ metrics     = [
- [
- "AWS/RDS",
- "CPUUtilization",
- "DBInstanceIdentifier",
- "login-dev-idp",
],
+ [
+ "AWS/RDS",
+ "CPUUtilization",
+ "DBInstanceIdentifier",
+ "login-dev-idp",
+ {
+ stat = "Maximum"
},
],
]
}
},
{
height     = 6
properties = {
annotations = {
horizontal = []
vertical   = []
}
metrics     = [
[
"AWS/RDS",
"ReadIOPS",
"DBInstanceIdentifier",
"login-dev-idp",
{
stat = "Maximum"
},
],
[
".",
"WriteIOPS",
".",
".",
{
stat = "Maximum"
},
],
]
period      = 300
region      = "us-west-2"
stacked     = false
title       = "R/W IOPS"
view        = "timeSeries"
yAxis       = {
left  = {
min = 0
}
right = {
min = 0
}
}
}
type       = …

Use min/max statistics in RDS dashboard

---

slo_lambda/main.tf
slo_lambda/src/windowed_slo_test.py
slo_lambda/variables.tf

Surprisingly, [EventBridge rules have a quota of ***5 targets per rule***](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-quota.html#eb-limits), so account-wide rules don't work with all of the env-specific targets from `cloudwatch_sli/slo_lambda`:
```
│ Error: Creating EventBridge Target failed: LimitExceededException: The requested resource exceeds the maximum number allowed.
```
This PR thus brings the `aws_cloudwatch_event_rule.every_one_day` back into the `slo_lambda` module, using the Lambda function name as an identifier in the name, and also re-adds `windowed_slo_test.py` which @akrito was using for development/testing.

restore every_one_day rule due to EventBridge quotas

---

slack_lambda/main.tf

I had some extra cycles so I wanted to try my hand at making our Slack alerts less visually noisy. I think the problem is the formatting of the `NewStateReason` from Cloudwatch
I wasn't sure exactly how to test this, since it looks like these lambdas are global for sandbox... but if all goes well, according to the [Slack BlockKit Editor](https://app.slack.com/block-kit-builder/T025AQGAN#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Alarm%20has%20gone%20off*:%20prod%20IDP%20Workers%20Failure%20Alert%5Cn_This%20alarm%20is%20executed%20when%20a%20worker%20job%20fails_%22%7D,%22accessory%22:%7B%22type%22:%22button%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22View%20Runbook%20:books:%22,%22emoji%22:true%7D,%22value%22:%22runboo …

Try to pretty format alerts with runbook links

---

dnssec/main.tf
versions.tf

While the general `terraform{}` block in `versions.tf` can be symlinked across directories, the `provider "aws"` causes conflicts when a module from this repo is called using `for_each` / `count` / etc., e.g.:
```
│ Error: Module module.main.module.slack_lambda_use1 contains provider configuration
│ 
│ Providers cannot be configured within modules using count, for_each or depends_on.
│ Error: Module module.main.module.slack_lambda_usw2 contains provider configuration
│ 
│ Providers cannot be configured within modules using count, for_each or depends_on.
```
This PR moves the provider alias block out of `versions.tf` and into `dnssec/main.tf`, as it is currently the only module in this repo that _requires_ an AWS provider in `us-east-1` (the only currently-supported region for AWS DNSSEC).

removing region-specific AWS provider aliases from versions.tf

---

iam_masterassume/main.tf
iam_masterusers/main.tf
ssm/README.md
ssm/main.tf
ssm/outputs.tf
ssm/variables.tf

_(This information is pulled directly from the `README` for the `ssm` module.)_
The `ssm` Terraform module is used to create SSM Documents for connecting to and running commands on AWS EC2 instances. Along with the documents themselves, this module creates:
1. An S3 bucket, and CloudWatch log group, for storing logs of SSM sessions (see note below) -- the S3 bucket is configured using [the `s3_config` module](https://github.com/18F/identity-terraform/tree/main/s3_config) from this repo
2. A second CloudWatch log group for logging when, and by whom, any given SSM document is used (via a CloudWatch event rule)
3. A KMS key + alias for encrypting the above resources (logs/bucket/objects), as well as the SSM sessions themselves
4. An IAM policy document (as a `data` source) that can be …

comprehensively-redesigned ssm module + accompanying updates to related iam_* modules

---

slack_lambda/main.tf
slo_lambda/main.tf

Somehow the commit got squashed and is breaking its parent modules as a result, e.g.:
```
│ Error: Failed to download module
│ 
│ Could not download module "lambda_zip" (.terraform/modules/cloudwatch_sli/slo_lambda/main.tf:68) source code from
│ "git::https://github.com/18F/identity-terraform.git?ref=aa0f4c1aaa13a6a46e9de2f9b7d8da430ce59527": error
│ downloading 'https://github.com/18F/identity-terraform.git?ref=aa0f4c1aaa13a6a46e9de2f9b7d8da430ce59527':
│ /usr/local/bin/git exited with 128: fatal: reference is not a tree: aa0f4c1aaa13a6a46e9de2f9b7d8da430ce59527
```

fixing orphaned gitshas for null_archive module references

---

dnssec/main.tf
ssm/main.tf

As per the title:
1. Updates the `dnssec` module to also depend upon the `aws_kms_key.dnssec` resource(s) before configure DNSSEC for the domain; without this additional dependency, DNSSEC can't be automatically disabled/the resource destroyed, e.g.:
```
Error: error disabling Route 53 Hosted Zone DNSSEC (Z0123456789ABCDEFGHI): KeySigningKeyInParentDSRecord: Disabling DNSSEC in hosted zone 'example.com.' will break the authentication chain. Please remove DS records in the parent zone first.
```
2. Updates the `ssm` module so that the `s3_config` block depends on `aws_s3_bucket.ssm_logs.arn`, meaning the module will wait for the bucket to exist before attempting to create the public access block/S3 Inventory configs.

adding depends_on blocks for ssm and dnssec modules

---

ssm/main.tf

Given the following key/value pair in a map variable, where the value is specifically declared as a bool:
```
use_root    = true
```
This directive in Terraform WILL work correctly...
```
%{if each.value["use_root"]}
```
...but ***this*** will ***NOT***:
```
%{if each.value["use_root"] == true}
```
What isn't immediately clear [from the documentation on Directives](https://www.terraform.io/language/expressions/strings#directives) is that Terraform processes boolean values of `true` / `false` as *strings*. Thus, the following directive in the `ssm` module will fail 100% of the time:
```
%{if each.value["use_root"] == false}
```
Updating the directive to look for a ***string*** (instead of a bool) corrects this issue for `ssm_doc_map` objects where `use_root = false`, as evidenced from the …

use string ("false") vs. bool (false) in directive for runAs* settings in SSM documents

---

iam_assumegroup/main.tf
iam_masterassume/main.tf
iam_masterusers/main.tf

AWS arns are unique for different partitions: 
- commercial accounts : "aws"
- govcloud: "aws-us-gov"
etc
This PR adjusts the arns in 
- Iam_assumegroup
- Iam_masterassume
- iam_masterusers
to be passed a different partition value if needed, but defaulting to the commercial 'aws' partition.

add support for govcloud in iam modules

---

elb_http_alerts/README.md
elb_http_alerts/main.tf

Since the name/description of the `aws_cloudwatch_metric_alarm` resources in this module is limited to just the environment name, this makes the module unable to create more than one set of alarms (i.e. for more than one Load Balancer in a single environment).
As a result, calling this module multiple times within a given moduleset will cause it to overwrite itself, e.g.:
Terraform plan:
```
~ resource "aws_cloudwatch_metric_alarm" "elb_http_5xx" {
~ dimensions = {
~ "LoadBalancer" = "login-app-elb-ENV" -> "arn:aws:elasticloadbalancing:us-west-2:111122223333:loadbalancer/app/login-idp-alb-ENV/0123456789abcdef"
~ resource "aws_cloudwatch_metric_alarm" "target_http_5xx" {
~ dimensions = {
~ "LoadBalancer" = "login-app-elb-ENV" -> "arn:aws:elasticloadbalancing:us-west-2:111122223333:loadbalan …
```

make elb_http_alerts module support multiple Load Balancers/types

---

elb_access_logs_bucket/main.tf
git2s3_artifacts/main.tf
git2s3_artifacts/outputs.tf
kms_log/main.tf
launch_template/main.tf
s3_bucket_block/main.tf
ssm/main.tf
state_bucket/main.tf
versions.tf

This primarily consists of updates to the `aws_s3_bucket` resource family. As of `v4.x` of the AWS Provider for Terraform, the various major attributes for the `aws_s3_bucket` resource have all been split out into individual resource types, e.g.:
- `aws_s3_bucket_server_side_encryption_configuration`
- `aws_s3_bucket_acl`
- `aws_s3_bucket_versioning`
- etc.
This PR breaks out those resources, as the aforementioned attributes for `aws_s3_bucket` resources are now deprecated. It also adds `instance_metadata_tags = "enabled"` to the `launch_template` module (ensuring that instances can access their tag metadata), updates some dependency/`count` blocks, and moves bucket logging to the `s3-access-logs` bucket (from `s3-logs`) as the latter has been deprecated within our own configurations.

update modules to support AWS Provider v4.x

---

elb_access_logs_bucket/main.tf
git2s3_artifacts/main.tf
kms_log/main.tf
s3_bucket_block/main.tf
slack_lambda/main.tf
slo_lambda/main.tf
ssm/main.tf
state_bucket/main.tf
versions.tf

This isn't actually used in any modules within this repo, and we're removing it from the one(s) we have downstream from it. Leaving it in causes Terraform to complain when trying to use a readonly lockfile (where it's no longer present), which is even more of an incentive to remove it!

remove deprecated hashicorp/template provider

---

elb_access_logs_bucket/main.tf
git2s3_artifacts/main.tf
kms_log/main.tf
s3_bucket_block/main.tf
slack_lambda/main.tf
slo_lambda/main.tf
ssm/main.tf
state_bucket/README.md
state_bucket/main.tf

While updating S3 resources/this repo's modules to AWS Provider v4 syntax was mostly a lengthy/toilsome process, we _do_ now have the ability to manage all of the resources for an S3 bucket -- whether or not Terraform creates the bucket itself. This helps to solve half of the chicken-and-egg problem of "how do we manage Terraform remote state resources _in Terraform itself_"; the bucket's ACLs/policy/versioning/inventory/logging config/etc. can all be managed separately after the bucket is created in the first place.
This also cleans up some formatting and updates the `README.md` for the module, which was out of date/using old formatting/references, and adds in some possible ways to deal with creating and importing these resources in Terraform state as seamlessly as possible.

updated state_bucket module with support for AWSv4 S3 resources

---

dnssec/README.md
dnssec/main.tf

[Lifecycle rules *still* (as of 2022-08-11) do not yet support interpolation](https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#literal-values-only), so we still can't conditionally set `prevent_destroy = true` for the DNSSEC signing/KMS/KSK resources.
However, since we ***are*** using `var.protect_resources` to conditionally create the `DNSSecDisablePrevent` IAM policy, we can add `prevent_destroy = true` to *that* as an additional way to guard against an accidental mass-`terraform destroy` operation against DNSSEC resources.
This PR adds that lifecycle rule, and updates the comments and `README` accordingly (along with including a link to [a new official Terraform issue](https://github.com/hashicorp/terraform/issues/30937), where discussion about said concepts is …

add prevent_destroy=true to optionally-created dnssec_disable_prevent policy

---

git2s3_artifacts/main.tf

Adds a '/' at the end of `target_prefix`, so all of the log files for 'public-artifacts' will go into their own folder instead of the root of the s3 bucket.

Add slash to target_prefix

---

iam_assumerole/main.tf

Addresses part of  [#5014](https://github.com/18F/identity-devops/issues/5014).  Adding support for conditions in iam policy documents:
- Adds output for iam_role
- Adds new optional `conditions` property in the `policy_document`
- Adds dynamic condition to add conditions to policies

Add iam output to iamassumerole

---

asg_recycle/README.md
asg_recycle/main.tf
asg_recycle/schedule.tf
asg_recycle/variables.tf

This PR updates the `asg_recycle` module to support a more complex configuration of scaling schedules, allowing one to define custom `cron` expressions for recycling and/or zeroing out hosts in ASGs.
Within `schedule.tf` is a local variable, `rotation_schedules`, which is a map of predefined schedules for recycling and/or zeroing out hosts, based on common scaling needs for ASGs:
- `*zero` schedules define how frequently (if at all) 'zero out' actions are run; the actions they create will spin up instances at 0500 and spin them down to 0 at 1600
- `norecycle` schedules do not create 'recycle' actions, regardless of whether or not 'zero out' actions are also created
- `normal` schedules create 4 'recycle' actions every day (at 0500 / 1100 / 1700 / 2300)
- `business` schedules create a …

support multiple/complex expressions/schedule combinations in asg_recycle module

---

asg_recycle/main.tf

When the number `-1` is provided to an `aws_autoscaling_schedule` resource, it translates to "don't touch this value" for whichever count type (Min/Max/Desired) it is pointing at; as a result, these schedules have traditionally only adjusted the Desired count by default. This PR fixes/updates the `autozero` schedules to follow the same template/formula, instead of setting all of the values for the ASGs to 0 (which can get in the way of the groups attempting to spin back up).
Additionally:
- If the Minimum count is 1 or more, and the Scheduled Action is attempting to spin DOWN an ASG, set Minimum to zero -- otherwise, leave it alone
- Similarly, if the Maximum count is 0 when attempting to spin UP a group, set it to 1 (and, similarly, leave it alone otherwise)

autozero schedules should not set min/max at 0

---

asg_recycle/main.tf
asg_recycle/variables.tf

Last (hopefully) tweak for the `asg_recycle` module -- this adds a new set of variables, all beginning with `normal`, which the `autozero-spinup` schedule uses to reset the target ASG back to its original numbers (when spinning back up from 0).
Using these variables negates the need to explicitly set the max/min/etc. for the other Scheduled Actions, which can still use the `-1` values as before.

fixing autozero schedules with new 'normal' vars

---

asg_recycle/main.tf

While the `asg_recycle` module has `for_each` logic in each resource -- to support the creation of multiple scheduled actions with the same counts and general name -- the resources all have the same static name, which causes Terraform to constantly loop through each schedule in its corresponding list and overwrite the Action accordingly, each time it runs. This adds a numerical iterator to the name of the Scheduled Action to prevent such resource clobbering.

add increments in action names when using multiple schedules in one Action

---

elb_http_alerts/main.tf
lambda_alerts/main.tf

In order to import an `aws_cloudwatch_metric_alarm` resource into Terraform state, one must supply the name of the alarm as an argument (which is also returned as the `id` of the created resource). This operation will fail if there are spaces in the name of the alarm, as `terraform import` only accepts 2 arguments (and gets confused by the spaces in the alarm name).
Therefore, this PR updates the various `aws_cloudwatch_metric_alarm` resources in this repo, replace the spaces in their names with hyphens and underscores.

remove spaces from CloudWatch metric alarm names

---

kms_log/main.tf
kms_log/variables.tf

A few tweaks to make it possible to use the `kms_log` module without agreeing to drop a message bomb on a SNS topic if things go awry.

Make kms_log more composable

---

guardduty/README.md
guardduty/main.tf
guardduty/outputs.tf
guardduty/variables.tf
guardduty/versions.tf

_(The below information is pulled directly from the README for the `guardduty` module.)_
This module creates and manages a GuardDuty Detector for an AWS account (in a single region), along with associated resources:
- S3 bucket used as a GuardDuty Publishing Destination + config resources (lifecycle/policy/logging/inventory/etc.)
- KMS key/alias for Publishing Destination and S3 SSE + key policy
- CloudWatch Event Rule triggered on GuardDuty Findings + Log Group / Event Target
```hcl
module "guardduty_usw2" {
source = "github.com/18F/identity-terraform//guardduty?ref=main"
region                     = "us-west-2"
bucket_name_prefix         = local.bucket_name_prefix
guardduty_finding_freq     = "SIX_HOURS"
guardduty_s3_enable        = true
guardduty_k8s_audit_enable = false …
```

creation of guardduty module (detector/CW logs/S3 destination/KMS keys)

---

kms_log/main.tf

Does what it says on the tin! I missed this in https://github.com/18F/identity-terraform/pull/154 but am fixing it here. Updates/corrects the alarm names thusly:
```
~ alarm_name = "Lambda error rate: bleachbyte-cloudtrail-kms" -> 
"LambdaErrorRate_bleachbyte-cloudtrail-kms" # forces replacement
...
~ alarm_name = "Lambda error rate: bleachbyte-cloudwatch-kms" -> 
"LambdaErrorRate_bleachbyte-cloudwatch-kms" # forces replacement
```

update lambda_alerts gitsha ref in kms_log module

---

ssm/main.tf

Does what it says on the tin! Given the signals from `stty -a`:
```
cchars: discard = ^O; dsusp = ^Y; eof = ^D; eol = <undef>;
eol2 = <undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;
min = 1; quit = ^\; reprint = ^R; start = ^Q; status = ^T;
stop = ^S; susp = ^Z; time = 0; werase = ^W;
```
...this change stops `CTRL+C`, `CTRL+Z`, `CTRL+D`, and `CTRL+\` (the other signals simply don't trigger any form of response).

also catch TERM in ssm_session Documents

---

elb_access_logs_bucket/main.tf
git2s3_artifacts/main.tf
guardduty/main.tf
kms_log/main.tf
s3_bucket_block/main.tf
slack_lambda/main.tf
slo_lambda/main.tf
ssm/main.tf
state_bucket/main.tf

Does what it says on the tin! This adds an additional commented-out 'source' line to each `module` block in this repo, which can be uncommented/switched with the gitsha 'source' for faster/simpler module interconnectivity, and/or if GitHub is unreachable by Terraform.

add/update local/relative-path 'source' lines

---

ssm/README.md
ssm/main.tf
ssm/outputs.tf
ssm/variables.tf

- Adds a new resource, `aws_ssm_document.ssm_interactive_cmd`, which creates `Session/InteractiveCommands` SSM documents based on the resource template (used for running single interactive commands with/without parameters)
- Removes `use_root` parameter from `aws_ssm_document.ssm_session` resources, since `aws_ssm_document.ssm_interactive_cmd` resources will run with elevated privileges (negating the need for a `root`-only `Standard_Session`)
- Updates the `aws_cloudwatch_event_rule.ssm_cmd` and `aws_cloudwatch_event_target.ssm_cmds` resources so that CloudWatch Events and Targets are created for ***all*** SSM documents created in this module, ensuring that all invocations of any SSM document are all fully logged in CloudWatch
- Updates the README and variable descriptions to be …

add InteractiveCommand doc creation + additional CW resources to ssm module

---

slo_lambda/main.tf
slo_lambda/variables.tf

Example: 
Corresponds to https://github.com/18F/identity-devops/pull/6005
<details>
<summary>Terraform will perform the following actions [in prod.]</summary>
```
+ resource "aws_cloudwatch_dashboard" "sli" {
+ dashboard_arn  = (known after apply)
+ dashboard_body = jsonencode(
{
+ widgets = [
+ {
+ height     = 9
+ properties = {
+ metrics = [
+ [
+ "prod/sli",
+ "idp-all_availability",
],
]
+ period  = 86400
+ region  = "us-west-2"
+ stacked = false
+ stat    = "Average"
+ title   = "all_availability over last 28 days"
+ view    = "timeSeries"
}
+ type       = "metric"
+ width      = 24
},
+ {
+ height     = 9
+ properties = {
+ metrics = [
+ [
+ "prod/sli",
+ "idp-interesting_availability",
],
]
+ period  = 86400
+ region  = "us-west-2"
+ stacked = false
+ stat    = "Average"
+ title …
```

Build an SLI dashboard

---

elb_access_logs_bucket/main.tf
git2s3_artifacts/main.tf
guardduty/main.tf
s3_bucket_block/main.tf
slo_lambda/main.tf
ssm/main.tf
state_bucket/main.tf

As [announced by AWS](https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/), Amazon S3 is disabling S3 access control lists (ACLs) for all new S3 buckets. As a result, using the `aws_s3_bucket_acl` resource to create an ACL for a bucket -- one which does not already have ownership controls in place -- will fail, unless bucket ownership has already been configured:
```terraform
│ Error: error creating S3 bucket ACL for <BUCKET-NAME-HERE>: AccessControlListNotSupported: The bucket does not allow ACLs
│ 
│   with aws_s3_bucket_acl.example_bucket,
│   on s3.tf line 8, in resource "aws_s3_bucket_acl" "example_bucket":
│    8: resource "aws_s3_bucket_acl" "example_bucket" {
```
Per the …

add BucketOwnerPreferred ownership controls to buckets w/ aws_s3_bucket_acl resources

---

ssm/main.tf

Allows proper escaping of multi-line strings, and commands with special YAML characters in it
~Uses [`yamlencode`](https://developer.hashicorp.com/terraform/language/functions/yamlencode), which is stable as of 1.4, but for earlier versions they recommend `jsonencode` instead~
~**Note**: I haven't tested this because I'm not 100% sure how to, also my Terraform syntax highlighting did not like the nested dictionaries, so that may not be possible~
This works because JSON is valid YAML

Use jsonencode() for string interpolation of commands

---

ssm/outputs.tf

Does what it says on the tin! Useful in situations where we need to reference the ARN of the KMS key created within this module.

add ssm_kms_arn output to ssm module

---

kms_log/main.tf
versions.tf

This PR modifies our KMS Matching Lambdas to use the latest ruby runtime available.

Updating KMS Matching to Ruby 3.2 Runtimes

---

kms_keymaker_multiregion_replica/cloudwatch.tf

This PR adds additional monitoring  to KMS Multi-Region Replica keys to prevent the promotion and replication of replica keys to primary without notification. As well as the replication after promotion.
Addresses #N/A

Replicate and Update-Primary-Region Replica Key Event Monitoring

---

kms_log/main.tf

This PR does what is says on the title. After applying the latest version of KMS Log, secondary applies result in a cycling error between the local_file and lambda resources.

Removing KMS Log replace_by_trigger due to cycling error

---

kms_log/main.tf
kms_log/variables.tf
lambda_alerts/main.tf

This PR enables Lambda Insights for KMS Log Module! In turn, this provides [useful performance metrics](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights-metrics.html) and memory alarms! Please note, sources for lambda_alerts will be updated to the corresponding  git SHA prior to merging.
_Related PRs:_
- https://github.com/18F/identity-terraform/pull/188
- https://github.com/18F/identity-devops/pull/6572
Partially Addresses #https://github.com/18F/identity-devops/issues/5916

Enable Lambda Insights for KMS Log Module

---

squid_cloudwatch_filters/main.tf

Terraform Plan:
```
~ resource "aws_cloudwatch_metric_alarm" "squid_denied_alarm" {
~ alarm_description         = <<-EOT
- Alarm when the Squid access log shows any denied requests [TF]
+ The outbound proxy has denied too many outbound requests.
+
+ Runbook: RUNBOOK_URL
EOT
id                        = "mhenke-squid-denials"
tags                      = {}
}
~ resource "aws_cloudwatch_metric_alarm" "squid_total_requests" {
~ alarm_description         = <<-EOT
- Alarm when the Squid access log total requests fall below threshold [TF]
+ The outbound proxy throughput is below the expected volume.
+
+ Runbook: RUNBOOK_URL
EOT
id                        = "mhenke-squid-total-requests"
tags                      = {}
}
```

Update outbound proxy alarm description to be more descriptive and include the runbook 
